# Google Maven
# https://maven.google.com/web/index.html?hl=zh-cn

# Gradle Plugins
# https://plugins.gradle.org/

# Maven
# https://mvnrepository.com/

[versions]
agp = "9.0.0"
biometric = "1.4.0-alpha05"
capsule = "2.1.3"
kotlin = "2.3.10"
ksp = "2.3.5"
composeBom = "2026.01.01"
compose = "1.10.2"
m3color = "2025.4"
haze = "1.7.1"
splashScreen = "1.2.0"
material3 = "1.5.0-alpha13"
room = "2.8.4"
ktx-serialization = "1.10.0"
accompanist = "0.37.3"
rikka-shizuku = "13.1.5"
koin-bom = "4.1.1"
datastore = "1.2.0"
aboutLibraries = "14.0.0-b02"
appiconloader = "1.5.0"
timber = "5.0.1"
miuix = "0.8.0-455c5ea-SNAPSHOT"
okhttp = "5.3.2"
monetcompat = "0.4.1"

[plugins]
agp-lib = { id = "com.android.library", version.ref = "agp" }
agp-app = { id = "com.android.application", version.ref = "agp" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
room = { id = "androidx.room", version.ref = "room" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
aboutLibraries = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "aboutLibraries" }

[libraries]
androidx-biometric = { module = "androidx.biometric:biometric", version.ref = "biometric" }
androidx-core = { group = "androidx.core", name = "core-ktx", version = "1.17.0" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version = "1.12.3" }
androidx-lifecycle = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version = "2.10.0" }
androidx-datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }
androix-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "splashScreen" }

capsule = { module = "io.github.kyant0:capsule", version.ref = "capsule" }
m3color = { module = "com.github.Kyant0:m3color", version.ref = "m3color" }
haze = { module = "dev.chrisbanes.haze:haze", version.ref = "haze" }
haze-materials = { module = "dev.chrisbanes.haze:haze-materials", version.ref = "haze" }
compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose" }
compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "compose" }
compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose" }
compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
compose-navigation = { group = "androidx.navigation", name = "navigation-compose", version = "2.9.7" }
compose-materialIcons = { group = "androidx.compose.material", name = "material-icons-extended", version = "1.7.8" }

room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }

# Kotlin Serialization
# https://github.com/Kotlin/kotlinx.serialization/blob/master/README.md#setup
# https://github.com/Kotlin/kotlinx.serialization/blob/master/formats/README.md
ktx-serializationJson = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "ktx-serialization" }
# kotlin reflect
kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "kotlin" }
# AndroidHiddenApiBypass
# https://github.com/LSPosed/AndroidHiddenApiBypass
hiddenapibypass = { group = "org.lsposed.hiddenapibypass", name = "hiddenapibypass", version = "6.1" }

# Koin Inject
# https://insert-koin.io/docs/setup/koin
koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin-bom" }
koin-core = { module = "io.insert-koin:koin-core" }
koin-android = { group = "io.insert-koin", name = "koin-android" }
koin-compose = { group = "io.insert-koin", name = "koin-androidx-compose" }
koin-compose-viewmodel = { group = "io.insert-koin", name = "koin-compose-viewmodel" }

accompanist-drawablepainter = { group = "com.google.accompanist", name = "accompanist-drawablepainter", version.ref = "accompanist" }

# Rikka Shizuku
# https://github.com/RikkaApps/Shizuku-API
rikka-shizuku-api = { group = "dev.rikka.shizuku", name = "api", version.ref = "rikka-shizuku" }
rikka-shizuku-provider = { group = "dev.rikka.shizuku", name = "provider", version.ref = "rikka-shizuku" }

# AppIconLoader
appiconloader = { module = "me.zhanghai.android.appiconloader:appiconloader", version.ref = "appiconloader" }

# Dhizuku-API
# https://github.com/iamr0s/Dhizuku-API
iamr0s-dhizuku-api = { group = "io.github.iamr0s", name = "Dhizuku-API", version = "2.5.4" }

# AndroidAppProcess
# https://github.com/iamr0s/AndroidAppProcess
# iamr0s-androidAppProcess = { group = "io.github.iamr0s", name = "AndroidAppProcess", version = "1.4.1" }
iamr0s-androidAppProcess = { group = "com.github.wxxsfxyzm", name = "AndroidAppProcess", version = "v1.4.1-revived" }

# Core module (required for accessing library data)
aboutlibraries-core = { module = "com.mikepenz:aboutlibraries-core", version.ref = "aboutLibraries" }
# Compose UI modules (choose one or both)
aboutlibraries-compose-m3 = { module = "com.mikepenz:aboutlibraries-compose-m3", version.ref = "aboutLibraries" } # Material 3 UI

# log
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }

# miuix
miuix = { group = "top.yukonga.miuix.kmp", name = "miuix-android", version.ref = "miuix" }
miuix-icons = { group = "top.yukonga.miuix.kmp", name = "miuix-icons-android", version.ref = "miuix" }

# okhttp
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }

# MonetCompat
# https://github.com/KieronQuinn/MonetCompat
monetcompat = { module = "com.github.KieronQuinn:MonetCompat", version.ref = "monetcompat" }
androidx-palette = { group = "androidx.palette", name = "palette", version = "1.0.0" }